// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKJ5msa2OSNTU0m-orn83q3dwfnQbhsU',
    appId: '1:366326053007:web:a6921242851242ef7fd8fa',
    messagingSenderId: '366326053007',
    projectId: 'deedz-eec37',
    authDomain: 'deedz-eec37.firebaseapp.com',
    storageBucket: 'deedz-eec37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBGEYjVixX9snmghCclTysEUcRIwSGGo',
    appId: '1:366326053007:android:0cc34f86a840acfd7fd8fa',
    messagingSenderId: '366326053007',
    projectId: 'deedz-eec37',
    storageBucket: 'deedz-eec37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_CvvOtJNynPd9Ni4R10x_YdusXzS7Mk',
    appId: '1:366326053007:ios:98ffe32e71378bc27fd8fa',
    messagingSenderId: '366326053007',
    projectId: 'deedz-eec37',
    storageBucket: 'deedz-eec37.appspot.com',
    iosBundleId: 'com.example.deedz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_CvvOtJNynPd9Ni4R10x_YdusXzS7Mk',
    appId: '1:366326053007:ios:98ffe32e71378bc27fd8fa',
    messagingSenderId: '366326053007',
    projectId: 'deedz-eec37',
    storageBucket: 'deedz-eec37.appspot.com',
    iosBundleId: 'com.example.deedz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTKJ5msa2OSNTU0m-orn83q3dwfnQbhsU',
    appId: '1:366326053007:web:84a3592d5c517a0a7fd8fa',
    messagingSenderId: '366326053007',
    projectId: 'deedz-eec37',
    authDomain: 'deedz-eec37.firebaseapp.com',
    storageBucket: 'deedz-eec37.appspot.com',
  );
}
